# app_index_trend.py - GannXPro (Advanced Market Trend Signals - Index Only)
# This file is generated by ChatGPT and adds an advanced "Market Trend Signals (Index Only)" tab
# Uses real NSE option-chain fetcher with a safe fallback and advanced analysis for NIFTY & BANKNIFTY.
import streamlit as st
import pandas as pd
import numpy as np
import requests
import yfinance as yf
from datetime import datetime, timedelta, date
import time as time_module

# ------------------- Page Setup -------------------
st.set_page_config(page_title="GannXPro — Index Trend Signals", page_icon="📈", layout="wide", initial_sidebar_state="expanded")

# Minimal CSS for clarity
st.markdown("""
<style>
    .main-header { font-size: 1.6rem; font-weight:700; color:#1f77b4; text-align:center; }
    .sub-header { font-size:0.9rem; color:#666; text-align:center; margin-bottom:10px; }
    .signal-box { padding:10px; border-radius:8px; margin-bottom:8px; }
    .sig-bull { background:#d4edda; border-left:6px solid #28a745; }
    .sig-bear { background:#f8d7da; border-left:6px solid #dc3545; }
    .sig-neutral { background:#fff3cd; border-left:6px solid #ffc107; }
    .small { font-size:0.85rem; color:#444; }
</style>
""", unsafe_allow_html=True)

st.markdown('<div class="main-header">📈 GannXPro — Market Trend Signals (Index Only)</div>', unsafe_allow_html=True)
st.markdown('<div class="sub-header">Advanced signals for NIFTY & BANKNIFTY using real NSE option-chain (with fallback)</div>', unsafe_allow_html=True)

# ------------------- Constants & Headers -------------------
NSE_HOME = "https://www.nseindia.com"
NSE_INDEX_ENDPOINT = "https://www.nseindia.com/api/option-chain-indices?symbol={symbol}"
HEADERS_BASE = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept": "application/json, text/javascript, */*; q=0.01",
    "Referer": "https://www.nseindia.com/option-chain"
}

# ------------------- Helpers -------------------
def _symbol_to_yf_ticker(symbol):
    if symbol == "NIFTY": return "^NSEI"
    if symbol == "BANKNIFTY": return "^NSEBANK"
    return symbol + ".NS"

@st.cache_data(ttl=8)
def get_live_price(symbol):
    """Get recent intraday price series and compute a few metrics"""
    try:
        ticker = _symbol_to_yf_ticker(symbol)
        df = yf.download(tickers=ticker, period='1d', interval='1m', progress=False, threads=True, timeout=10)
        if df is None or df.empty:
            return None
        hist = df.dropna()
        if hist.empty:
            return None
        current = float(hist['Close'].iloc[-1])
        openp = float(hist['Open'].iloc[0])
        high = float(hist['High'].max())
        low = float(hist['Low'].min())
        volume = int(hist['Volume'].iloc[-1]) if 'Volume' in hist.columns else 0
        change_today = ((current - openp)/openp)*100 if openp!=0 else 0.0
        # compute 5m change
        prev_idx = max(0, len(hist)-6)
        prev_close = float(hist['Close'].iloc[prev_idx])
        change_5m = ((current - prev_close)/prev_close)*100 if prev_close!=0 else 0.0
        # 15m change
        prev_idx15 = max(0, len(hist)-16)
        prev_close15 = float(hist['Close'].iloc[prev_idx15])
        change_15m = ((current - prev_close15)/prev_close15)*100 if prev_close15!=0 else 0.0
        return {
            'current': current,
            'open': openp,
            'high': high,
            'low': low,
            'volume': volume,
            'change': change_today,
            'change_5m': change_5m,
            'change_15m': change_15m,
            'timestamp': datetime.now(),
            'hist': hist
        }
    except Exception as e:
        return None

# ------------------- NSE Option Chain Fetcher -------------------
@st.cache_data(ttl=12)
def fetch_nse_option_chain_index(symbol):
    """Fetch option chain for NIFTY or BANKNIFTY from NSE. Returns parsed dict or None on failure."""
    session = requests.Session()
    session.headers.update(HEADERS_BASE)
    try:
        # get cookies by visiting homepage
        session.get(NSE_HOME, timeout=10)
        url = NSE_INDEX_ENDPOINT.format(symbol=symbol)
        resp = session.get(url, timeout=10)
        if resp.status_code != 200:
            # try again with referer
            session.headers.update({"Referer":"https://www.nseindia.com/live_market/dynaContent/live_watch/option_chain/optionKeys.jsp"})
            resp = session.get(url, timeout=10)
        resp.raise_for_status()
        data = resp.json()
        parsed = {'success':True, 'symbol':symbol, 'timestamp':datetime.now().strftime("%d-%b-%Y %H:%M:%S"), 'option_data':[], 'underlying': None, 'expiries': []}
        records = data.get('records', {})
        parsed['underlying'] = records.get('underlyingValue') or data.get('underlyingValue')
        parsed['expiries'] = records.get('expiryDates') or []
        rows = records.get('data') or []
        total_ce = total_pe = 0
        for row in rows:
            ce = row.get('CE')
            pe = row.get('PE')
            strike = row.get('strikePrice') or row.get('strike')
            if ce:
                parsed['option_data'].append({**ce, 'type':'CE','strike':strike})
                total_ce += int(ce.get('openInterest') or 0)
            if pe:
                parsed['option_data'].append({**pe, 'type':'PE','strike':strike})
                total_pe += int(pe.get('openInterest') or 0)
        parsed['total_ce_oi'] = total_ce
        parsed['total_pe_oi'] = total_pe
        parsed['pcr'] = (total_pe / total_ce) if total_ce>0 else None
        return parsed
    except Exception:
        return None

# ------------------- Fallback Generator -------------------
def generate_index_option_chain_fallback(symbol):
    """Synthetic option chain if NSE fetch fails. Simpler, consistent with index step sizes."""
    base = 21500 if symbol=='NIFTY' else 48000
    base += np.random.randint(-100,100)
    step = 100
    strikes = [base + i*step for i in range(-8,9)]
    option_data = []
    for s in strikes:
        dist = abs(s - base)
        iv = 12 + (dist/base)*100 + np.random.uniform(-2,2)
        option_data.append({'type':'CE','strike':s,'expiry':(date.today()+timedelta(days=7)).strftime("%d-%b-%Y"),'oi':int(max(500, 20000/(dist+100)*np.random.uniform(0.8,1.2))),'volume':int(max(100,2000/(dist+100)*np.random.uniform(0.6,1.4))),'iv':round(iv,1),'ltp':round(max(1,dist*0.1*np.random.uniform(0.8,1.2)),2)})
        option_data.append({'type':'PE','strike':s,'expiry':(date.today()+timedelta(days=7)).strftime("%d-%b-%Y"),'oi':int(max(500, 23000/(dist+100)*np.random.uniform(0.8,1.2))),'volume':int(max(100,2500/(dist+100)*np.random.uniform(0.6,1.4))),'iv':round(iv+1,1),'ltp':round(max(1,dist*0.1*np.random.uniform(0.8,1.2)),2)})
    total_ce = sum([o['oi'] for o in option_data if o['type']=='CE'])
    total_pe = sum([o['oi'] for o in option_data if o['type']=='PE'])
    return {'success':True,'symbol':symbol,'option_data':option_data,'underlying':base,'total_ce_oi':total_ce,'total_pe_oi':total_pe,'pcr':(total_pe/total_ce if total_ce>0 else None),'expiries':[(date.today()+timedelta(days=7)).strftime("%d-%b-%Y")]}

# ------------------- Analysis Utilities -------------------
def aggregate_atm(option_rows, spot, step=100):
    """Aggregate OI and volume at ATM strike (closest)."""
    if not option_rows: return {'ce_oi':0,'pe_oi':0,'ce_vol':0,'pe_vol':0,'atm_strike':None}
    # find closest strike
    strikes = sorted(set([r['strike'] for r in option_rows if r.get('strike') is not None]))
    atm = min(strikes, key=lambda x: abs(x - spot))
    ce_oi = pe_oi = ce_vol = pe_vol = 0
    for r in option_rows:
        if r.get('strike') == atm:
            if r.get('type') == 'CE':
                ce_oi += int(r.get('openInterest') or r.get('oi',0))
                ce_vol += int(r.get('totalTradedVolume') or r.get('volume',0))
            else:
                pe_oi += int(r.get('openInterest') or r.get('oi',0))
                pe_vol += int(r.get('totalTradedVolume') or r.get('volume',0))
    return {'ce_oi':ce_oi,'pe_oi':pe_oi,'ce_vol':ce_vol,'pe_vol':pe_vol,'atm_strike':atm}

def detect_index_trend(symbol, option_payload, price_payload):
    """Advanced heuristics to produce a signal and reason for NIFTY/BANKNIFTY."""
    if not option_payload or not price_payload:
        return {'signal':'NO_DATA','reason':'Missing data'}
    spot = option_payload.get('underlying') or price_payload.get('current')
    option_rows = option_payload.get('option_data') or []
    atm = aggregate_atm(option_rows, spot, step=100)
    total_ce = option_payload.get('total_ce_oi') or 0
    total_pe = option_payload.get('total_pe_oi') or 0
    pcr = option_payload.get('pcr')
    # price moves
    change_5m = price_payload.get('change_5m') or 0
    change_15m = price_payload.get('change_15m') or 0
    change_today = price_payload.get('change') or 0
    # Heuristics (advanced):
    # Short covering: price rising strongly and ATM PE OI > ATM CE OI (puts being bought to hedge) or rising PCR + price up
    if change_5m > 0.3 and (atm['pe_oi'] > atm['ce_oi']*1.05 or (pcr and pcr>1.05)):
        return {'signal':'SHORT_COVERING','reason':f'5m {change_5m:.2f}% up; ATM_PE_OI {atm["pe_oi"]} > ATM_CE_OI {atm["ce_oi"]}; PCR {pcr}' , 'atm':atm, 'pcr':pcr}
    # Long unwinding: price falling and ATM CE OI > ATM PE OI
    if change_5m < -0.3 and (atm['ce_oi'] > atm['pe_oi']*1.05 or (pcr and pcr<0.95)):
        return {'signal':'LONG_UNWINDING','reason':f'5m {change_5m:.2f}% down; ATM_CE_OI {atm["ce_oi"]} > ATM_PE_OI {atm["pe_oi"]}; PCR {pcr}', 'atm':atm, 'pcr':pcr}
    # Call buying: price up and ATM CE volume > ATM PE volume
    if change_15m > 0.4 and atm['ce_vol'] > atm['pe_vol']*1.3:
        return {'signal':'CALL_BUYING','reason':f'15m {change_15m:.2f}% up; ATM_CE_VOL {atm["ce_vol"]} > ATM_PE_VOL {atm["pe_vol"]}', 'atm':atm, 'pcr':pcr}
    # Put buying: price down and ATM PE volume > ATM CE volume
    if change_15m < -0.4 and atm['pe_vol'] > atm['ce_vol']*1.3:
        return {'signal':'PUT_BUYING','reason':f'15m {change_15m:.2f}% down; ATM_PE_VOL {atm["pe_vol"]} > ATM_CE_VOL {atm["ce_vol"]}', 'atm':atm, 'pcr':pcr}
    # Sideways
    if abs(change_today) < 0.05 and abs(change_5m) < 0.1:
        return {'signal':'SIDEWAYS','reason':f'Little movement; Today {change_today:.2f}%; 5m {change_5m:.2f}%', 'atm':atm, 'pcr':pcr}
    return {'signal':'NO_CLEAR_SIGNAL','reason':f'5m {change_5m:.2f}%; 15m {change_15m:.2f}%; PCR {pcr}', 'atm':atm, 'pcr':pcr}

# ------------------- Hero-Zero Scanner (Index) -------------------
def hero_zero_candidates_index(option_payload, spot):
    """Return CE strikes near ATM with low-moderate IV and reasonable volume"""
    if not option_payload: return []
    rows = option_payload.get('option_data', [])
    candidates = []
    atm = min(sorted(set([r['strike'] for r in rows])), key=lambda x: abs(x-spot))
    steps = [100,200,300]
    for s in [atm + step for step in steps] + [atm - step for step in steps]:
        # find CE for strike s
        ce = next((r for r in rows if r['strike']==s and r.get('type')=='CE'), None)
        if ce:
            iv = float(ce.get('impliedVolatility') or ce.get('iv') or 0)
            vol = int(ce.get('totalTradedVolume') or ce.get('volume') or 0)
            if iv < 28 and vol > 100:
                candidates.append({'strike':s,'iv':iv,'volume':vol,'ltp':ce.get('lastPrice') or ce.get('ltp')})
    return candidates

# ------------------- UI: Controls -------------------
col1, col2 = st.columns([3,1])
with col1:
    st.markdown(f"**Last Updated:** {datetime.now().strftime('%d-%b-%Y %H:%M:%S')}")
with col2:
    if st.button("🔄 Refresh Now"):
        st.experimental_rerun()

st.sidebar.header("Index Signals")
mode = st.sidebar.selectbox("Choose view", ["Summary", "Detailed - NIFTY", "Detailed - BANKNIFTY"], index=0)
st.sidebar.markdown("Advanced analysis uses NSE option-chain when available. If NSE blocks the request, a synthetic fallback is used.")

# ------------------- Core Flow -------------------
indices = ['NIFTY','BANKNIFTY']

# Fetch data for both indices
with st.spinner("Fetching option chains and prices for indices..."):
    data = {}
    for idx in indices:
        opt = fetch_nse_option_chain_index(idx)
        if not opt:
            opt = generate_index_option_chain_fallback(idx)
        price = get_live_price(idx)
        trend = detect_index_trend(idx, opt, price)
        hero = hero_zero_candidates_index(opt, opt.get('underlying') if opt else (price.get('current') if price else None))
        data[idx] = {'option': opt, 'price': price, 'trend': trend, 'hero': hero}

# ------------------- Summary View -------------------
if mode == "Summary":
    st.markdown("## Market Trend Summary (NIFTY & BANKNIFTY)")
    cols = st.columns(2)
    for i, idx in enumerate(indices):
        with cols[i]:
            d = data[idx]
            trend = d['trend']['signal']
            reason = d['trend']['reason']
            atm = d['trend'].get('atm') or {}
            pcr = d['trend'].get('pcr') or d['option'].get('pcr') if d.get('option') else None
            price = d['price']['current'] if d.get('price') else None
            if trend == 'SHORT_COVERING':
                cl = "sig-bull"; title = "🟢 SHORT COVERING"
            elif trend == 'LONG_UNWINDING':
                cl = "sig-bear"; title = "🔴 LONG UNWINDING"
            elif trend == 'CALL_BUYING':
                cl = "sig-bull"; title = "📈 CALL BUYING"
            elif trend == 'PUT_BUYING':
                cl = "sig-bear"; title = "📉 PUT BUYING"
            elif trend == 'SIDEWAYS':
                cl = "sig-neutral"; title = "🟡 SIDEWAYS"
            else:
                cl = "sig-neutral"; title = "❔ NO CLEAR SIGNAL"
            st.markdown(f"<div class='signal-box {cl}'><strong>{idx} — {title}</strong><div class='small'>{reason}</div></div>", unsafe_allow_html=True)
            st.write(f"Price: ₹{price if price else 'N/A'} | PCR: {pcr if pcr else 'N/A'}")
            st.write(f"ATM Strike: {atm.get('atm_strike')}  | ATM CE OI: {atm.get('ce_oi')}  | ATM PE OI: {atm.get('pe_oi')}")
            # show hero candidates small table
            if d['hero']:
                hdf = pd.DataFrame(d['hero'])
                st.write("Hero-Zero CE candidates:")
                st.dataframe(hdf)
            else:
                st.write("No Hero-Zero CE candidates found (index scan).")

    st.markdown("---")
    st.info("Advanced view includes ATM-level OI, volume, PCR and heuristics combining price & OI. These are heuristics, not financial advice.")

# ------------------- Detailed View per Index -------------------
else:
    idx = "NIFTY" if mode.endswith("NIFTY") else "BANKNIFTY"
    st.markdown(f"## Detailed View — {idx}")
    d = data[idx]
    price = d.get('price')
    opt = d.get('option')
    trend = d.get('trend')
    hero = d.get('hero')

    # Top row: price and key metrics
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Live Price", f"₹{price['current']:.2f}" if price else "N/A")
    c2.metric("PCR", f"{opt.get('pcr'):.2f}" if opt else "N/A")
    c3.metric("ATM CE OI", f"{trend.get('atm')['ce_oi'] if trend.get('atm') else 'N/A'}")
    c4.metric("ATM PE OI", f"{trend.get('atm')['pe_oi'] if trend.get('atm') else 'N/A'}")

    st.markdown("### Trend Signal")
    sig = trend['signal']
    st.write(f"**Signal:** {sig} — {trend['reason']}")

    # ATM panel
    st.markdown("### ATM Summary")
    atm = trend.get('atm') or {}
    atm_df = pd.DataFrame([{'ATM Strike': atm.get('atm_strike'), 'CE OI': atm.get('ce_oi'), 'PE OI': atm.get('pe_oi'), 'CE Volume': atm.get('ce_vol'), 'PE Volume': atm.get('pe_vol')}])
    st.table(atm_df)

# Heatmap and OI table
    st.markdown("### OI Heatmap (sample pivot)")
    rows = opt.get('option_data') if opt else []
    if rows:
        df = pd.DataFrame(rows)
        # normalize keys for fallback synthetic data
        if 'openInterest' in df.columns:
            df['oi'] = df['openInterest']
        if 'totalTradedVolume' in df.columns:
            df['vol'] = df['totalTradedVolume']
        if 'lastPrice' in df.columns:
            df['ltp'] = df['lastPrice']
        pivot = df.pivot_table(index='strike', columns='type', values='oi', aggfunc='sum').fillna(0)
        # show sample heat (as numbers). visual styling more advanced would require AgGrid or altair heatmap.
        st.dataframe(pivot.sort_index(ascending=False).head(30))

    # Hero-zero candidates
    st.markdown("### Hero-Zero Candidates (detailed)")
    if hero:
        st.dataframe(pd.DataFrame(hero))
    else:
        st.write("No candidates found for hero-zero strategy based on current filters.")

    # Show top option chain rows
    st.markdown("### Sample Option Rows (top 50)")
    if rows:
        srows = df[['type','strike','oi','vol','iv','ltp']].sort_values(['strike','type']).head(50)
        st.dataframe(srows)

    st.markdown("---")
    st.info("This detailed view uses real NSE option-chain when available. For production, consider snapshotting OI over time to compute true OI deltas (best practice).")

# Footer
st.markdown("""---
<div style='text-align:center;color:#666;'>
    <p><strong>GannXPro — Index Trend Signals</strong></p>
    <p>Educational purposes only. Not financial advice.</p>
</div>
""", unsafe_allow_html=True)
